color0 #083149
color1 #ce7033
color2 #59d4f3
color3 #dc8b56
color4 #8276ff
color5 #88e0f6
color6 #e9b695
color7 #f2f3f3
color8 #626e71
color9 #ce7033
color10 #59d4f3
color11 #dc8b56
color12 #8276ff
color13 #88e0f6
color14 #e9b695
color15 #f2f3f3

cursor                #f2f3f3
cursor_text_color     #042539
background            #042539
foreground            #f2f3f3
selection_foreground  #afb5b6
selection_background  #083149
active_border_color   #59d4f3
inactive_border_color #083149
url_color             #59d4f3

active_tab_foreground   #182225
active_tab_background   #59d4f3
inactive_tab_foreground #afb5b6
inactive_tab_background #083149
cursor_trail_color      #afb5b6
