
# Fonts
font_family      Vicotr Mono
#font_size        13

# Appearance
background_opacity 0.90
hide_window_decorations yes
tab_bar_style powerline

# Include a theme file if desired
# include ./my-theme.conf   

include themes/noctalia.conf
